

name: SelfCommit
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  self_commit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Commit lol
        run: |
          while true; do
            git pull origin main || echo "No changes to pull"
            echo "$(date)" > timestamp.txt
            git add timestamp.txt
            git config user.name "ThePixelMoon"
            git config user.email "yourlocalmoon7@gmail.com"
            git commit -m "update at $(date)" || echo "No changes"
            git push https://$PAT_TOKEN@github.com/${{ github.repository }}.git HEAD:main
          done
        shell: bash
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
